--- 
apiVersion: v1
kind: BuildConfig
metadata: 
  annotations: ~
  creationTimestamp: ~
  labels: 
    app: pipeline
    name: pipeline
  name: pipeline
spec: 
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source: 
    secrets: ~
    type: None
  strategy: 
    jenkinsPipelineStrategy: 
      jenkinsfile: "#!groovy\n"
    type: JenkinsPipeline
