apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: on-demand
    name: on-demand
  name: on-demand
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "#!groovy\n\n// jenkins environment variables\necho \"Build Number
        is: ${env.BUILD_NUMBER}\"\n\ndef devAppName  = \"myapp-dev-${env.BUILD_NUMBER}\"\ndef
        gitUrl = 'http://gogs-gogs.192.168.137.3.xip.io/developer/cotd'\ndef gitBranch
        = 'master'\n\nnode('maven') {\n  stage 'build & deploy in dev'\n  \n  sh \"oc
        new-app -o yaml --name=${devAppName} openshift/php:5.6~${gitUrl}#${gitBranch}
        > /tmp/${devAppName}.yaml\"\n  yamlConfig = readFile \"/tmp/${devAppName}.yaml\"\n
        \ openshiftCreateResource(namespace: 'development',\n        yaml: \"${yamlConfig}\")\n
        \ sh \"rm -f /tmp/${devAppName}.yaml\"\n  sh \"oc project development && oc
        expose -o yaml svc ${devAppName}\"\n  \n  stage 'verify deploy in dev'\n  openshiftVerifyDeployment(namespace:
        'development',\n\t\t\t\t       depCfg: \"${devAppName}\",\n\t\t\t\t       replicaCount:'1',\n\t\t\t\t
        \      verifyReplicaCount: 'true',\n\t\t\t\t       waitTime: '300000')\n  stage
        'delete on-demand apps'\n  timeout(time: 7, unit: 'DAYS') {\n        input
        'Delete Apps?'\n        echo 'Delete Apps'\n        sh \"oc delete all -l
        app=${devAppName} -n development\"\n  }\n}\n"
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0
